# Uncomment this file to enable multilanguage site support

[en]
languageName = "English"
languagedirection = "ltr"
title = "Welcome to Unili's Blog"
weight = 1

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "Welcome to Unili's Blog"
weight = 1